### ISSUE TITLE
TOKEL Wallet

### ISSUE THREAD

**Issue by piggydoughnut** [TokelPlatform/tokel_app#1]
- [x] Create the main Wallet view
  - [x] Style the dashboard frame Issue: #9 
  - [x] Listing of coins/tokens owned by the user
  - [ ] connect it to TKLTEST
  - [x] Portoflio value graph Issue: #10 
  - [x] Recent Activity for all tokens/coins Issue: #11
  - [x] Pie chart graph for assets Issue: #13 
 
- [x] Detail for each coin/token (click on the token/coin in the left menu -> The right widgets change)
    - [x] Portfolio value graph just for this token/coin
    - [x] Recent activity about the given token/coin -> listing
      - [x] Click on detail on recent activity opens a pop up with information
    - [x] Wallet tab option (information + send, receive buttons) Issue : #26 
      - [x] Receive -> pop up with a qr coded address, address and a notice
      - [x] Send -> Enter address, how much, send.
