### ISSUE TITLE
Designs - Release, Roadmap

### ISSUE THREAD

**Issue by piggydoughnut** [TokelPlatform/tokel_app#71]
- [x] designs for release announcement on the main page
- [x] design for the roadmap
- [x] implement release announcement
- [x] implement roadmap

**Comment by piggydoughnut** [comment]
![header-before-release](https://user-images.githubusercontent.com/2395326/119472635-fb05fc80-bd7c-11eb-9e2d-100ae46ddba1.png)

![header-mobile](https://user-images.githubusercontent.com/2395326/119472658-ff321a00-bd7c-11eb-8414-94b8cda2d132.png)


![header-release](https://user-images.githubusercontent.com/2395326/119472696-0822eb80-bd7d-11eb-87e8-7141f8709453.png)

**Comment by piggydoughnut** [comment]
![roadmapv2](https://user-images.githubusercontent.com/2395326/119473277-97300380-bd7d-11eb-8373-c6c011e572ef.png)
